
# This file is automatically generated by setup.py
short_version = '0.0.0'
version = '0.0.0'
full_version = '0.0.0.dev-42a0b43'
git_revision = '42a0b4362af481b6225b7763b497f8ca1318625d'
release = False

if not release:
    version = full_version
